const Set<String> englishCussWords = {
  "fuck", "fucking", "fucked", "fucker", "fucks", "fuckup", "fuckface",
  "motherfucker", "motherfucking", "fuckhead", "clusterfuck", "dumbfuck",
  "shit", "shits", "shitty", "bullshit", "shithead", "shitbag", "dipshit",
  "shitface", "shithole",
  "bitch", "bitches", "bitchy", "bastard", "bastards",
  "ass", "asses", "asshole", "assholes", "asshat", "dumbass", "jackass", "smartass",
  "dick", "dicks", "dickhead", "cock", "cockhead", "knob", "knobhead", "bellend",
  "pussy", "pussies", "cunt", "cunts", "minge", "twat",
  "prick", "wanker", "tosser", "arsehole", "bollocks", "bloody",
  "jerk", "moron", "idiot", "retard", "retarded", "spastic", "douchebag", "douche",
  "slut", "sluts", "whore", "hooker", "skank",
  "crap", "crappy", "piss", "pissed", "pissoff",
};

const Set<String> hindiCussWords = {
  "gandu", "gaandu",
  "bhenchod", "bhenchood", "behenchod", "bhenke",
  "madarchod", "madarchood", "maderchod",
  "chutiya", "chutiye", "chutiyapa", "chut", "choot",
  "randi", "randwa", "randa", "randapa",
  "harami", "haramzada", "haramzadi", "haramkhor",
  "kamina", "kaminey", "kameena",
  "launde", "launda", "lodu", "loda",
  "lund", "lavde", "lavda", "lavdya", "laude",
  "bhosdike", "bhosdiwala", "bhosdi",
  "suar", "kutte", "kuttey", "kuttiya",
  "chod", "chodna", "chodu",
  "gaand", "gand",
  "saala", "sali",
  "chakka", "hijra",
  "bhadwa", "bhadwi",
  "dalal",
};

const Set<String> malayalamCussWords = {
  "kunna", "kunne",
  "myre", "myren", "myru", "myr", "mayre", "mayran", "myran", "myranmare",
  "mayir", "mairu", "maiyr", "mayiru",
  "koon", "kooni",
  "punda", "punde", "pundan", "pundachi", "pundachiye", "pundakke", "pundamare", "pundakku",
  "poori", "pooru", "poore", "pooran", "poorr",
  "koothi", "koothiyal", "koothy", "kooti", "kuthi",
  "potte", "potti",
  "kundi", "kundiyan", "kundimare",
  "oomb", "oombu", "oombi", "oomban", "oombiko", "oombikko", "oombiyan",
  "oombanmare", "oombanmar",
  "thayoli", "thayoley", "thayolikku", "thayolikal",
  "thallayoli", "thalayoli",
  "ammayoli", "ammayolikku",
  "thevidichi", "thevidiya", "thevidichiye",
  "koothichi", "koothara",
  "vedi", "veedi",
  "pottan", "pottichi", "pottanmar",
  "mandan", "manthan", "manthichi",
  "mondan", "mondathi",
  "mutthal", "mutthan", "muthal", "muthan",
  "thendi",
  "kazhuthai", "kazhuthaye",
  "aanpatti", "aampatti",
  "naaye", "naye", "nayinte",
  "panni",
  "kazhuveri",
  "porki", "porkikal",
  "chattambi",
  "onnan", "onnathi",
  "kotha", "kotham",
  "poda", "podi",
};

const Set<String> allCussWords = {
  ...englishCussWords,
  ...hindiCussWords,
  ...malayalamCussWords,
};
